# Left leg
l_knee: -1.05
l_ankle_pitch: -0.57
l_ankle_roll: -0.024
l_hip_pitch: 0.48
l_hip_roll: 0.023
l_hip_yaw: -0.005
# Left arm
l_elbow: 0.54
l_wrist_pitch: 0.0
l_wrist_prosup: 0.0
l_wrist_yaw: 0.0
l_shoulder_pitch: -0.159
l_shoulder_roll: 2.0
l_shoulder_yaw: 0.183
# Head
neck_pitch: -0.50
neck_roll: 0.0
neck_yaw: 0.0
# Right leg
r_knee: -1.05
r_ankle_pitch: -0.57
r_ankle_roll: -0.024
r_hip_pitch: 0.48
r_hip_roll: 0.023
r_hip_yaw: -0.005
# Right arm
r_elbow: 1.7
r_wrist_pitch: 0.0
r_wrist_prosup: -0.5
r_wrist_yaw: 0.0
r_shoulder_pitch: -0.159
r_shoulder_roll: 1.3
r_shoulder_yaw: 0.183
# Torso
torso_pitch: 0.1
torso_roll: 0.0
torso_yaw: 0.0
# Left hand
l_hand_finger: 0.0
l_thumb_oppose: 1.5708
l_thumb_proximal: 0.0
l_thumb_distal: 0.0
l_index_proximal: 0.0
l_index_distal: 0.0
l_middle_proximal: 0.0
l_middle_distal: 0.0
l_pinky: 0.0
# Right hand
r_hand_finger: 0.01
r_thumb_oppose: 1.5708
r_thumb_proximal: 0.01
r_thumb_distal: 0.01
r_index_proximal: 0.01
r_index_distal: 0.01
r_middle_proximal: 0.01
r_middle_distal: 0.01
r_pinky: 0.3