# Left leg
l_knee: -1.05
l_ankle_pitch: -0.57
l_ankle_roll: -0.024
l_hip_pitch: 0.48
l_hip_roll: 0.023
l_hip_yaw: -0.005
# Left arm
l_elbow: 0.54
l_wrist_pitch: 0.0
l_wrist_prosup: 0.0
l_wrist_yaw: 0.0
l_shoulder_pitch: -0.159
l_shoulder_roll: 2.0
l_shoulder_yaw: 0.183
# Head
neck_pitch: 0.0
neck_roll: 0.0
neck_yaw: 0.0
# Right leg
r_knee: -1.05
r_ankle_pitch: -0.57
r_ankle_roll: -0.024
r_hip_pitch: 0.48
r_hip_roll: 0.023
r_hip_yaw: -0.005
# Right arm
r_elbow: 0.54
r_wrist_pitch: 0.0
r_wrist_prosup: 0.0
r_wrist_yaw: 0.0
r_shoulder_pitch: -0.159
r_shoulder_roll: 2.0
r_shoulder_yaw: 0.183
# Torso
torso_pitch: 0.1
torso_roll: 0.0
torso_yaw: 0.0
# Right hand
r_hand_thumb_0_joint: 0.7854
r_hand_thumb_1_joint: 0.7854
r_hand_thumb_2_joint: 0.7854
r_hand_thumb_3_joint: 0.7854
r_hand_index_0_joint: -0.15
r_hand_index_1_joint: 0.7854
r_hand_index_2_joint: 0.7854
r_hand_index_3_joint: 0.7854
r_hand_middle_0_joint: 0.15
r_hand_middle_1_joint: 0.7854
r_hand_middle_2_joint: 0.7854
r_hand_middle_3_joint: 0.7854
r_hand_ring_0_joint: 0.15
r_hand_ring_1_joint: 0.7854
r_hand_ring_2_joint: 0.7854
r_hand_ring_3_joint: 0.7854
r_hand_little_0_joint: 0.15
r_hand_little_1_joint: 0.7854
r_hand_little_2_joint: 0.7854
r_hand_little_3_joint: 0.7854
# Left hand
l_hand_thumb_0_joint: 0.7854
l_hand_thumb_1_joint: 0.7854
l_hand_thumb_2_joint: 0.7854
l_hand_thumb_3_joint: 0.7854
l_hand_index_0_joint: -0.15
l_hand_index_1_joint: 0.7854
l_hand_index_2_joint: 0.7854
l_hand_index_3_joint: 0.7854
l_hand_middle_0_joint: 0.15
l_hand_middle_1_joint: 0.7854
l_hand_middle_2_joint: 0.7854
l_hand_middle_3_joint: 0.7854
l_hand_ring_0_joint: 0.15
l_hand_ring_1_joint: 0.7854
l_hand_ring_2_joint: 0.7854
l_hand_ring_3_joint: 0.7854
l_hand_little_0_joint: 0.15
l_hand_little_1_joint: 0.7854
l_hand_little_2_joint: 0.7854
l_hand_little_3_joint: 0.7854
