# SPDX-FileCopyrightText: 2023 Humanoid Sensing and Perception, Istituto Italiano di Tecnologia
# SPDX-License-Identifier: BSD-3-Clause

# Right hand
r_hand_freejoint: [0.0, 0.0, 1.5, 0.707106781, 0.707106781, 0, 0]
r_hand_finger: 0.01
r_thumb_oppose: 1.5708
r_thumb_proximal: 0.01
r_thumb_distal: 0.01
r_index_proximal: 0.01
r_index_distal: 0.01
r_middle_proximal: 0.01
r_middle_distal: 0.01
r_pinky: 0.3